### ISSUE TITLE
Exception: Please provide ShowCaseView context

### ISSUE THREAD

**Issue by mohadel92** [SimformSolutionsPvtLtd/flutter_showcaseview#219]
**Describe the bug**
i am using Getx state management in my app
and everything is working fine
now i want to use showcase view but i always get an error with  "Please provide ShowCaseView context"

i tried to wrap my initial widget(splash) and it failed then i wrapped each page in my bottom nav bar and it failed 
i tried to wrap the complete  bottom nav bar ( i am using persistent bottom nav bar) and it also failed

**To Reproduce**
1. install getx and persistent nav bat
2. wrap your initial widget with showcaseWidget
3. call ShowCaseWidget.of(Get.context)?.startShowCase([_key1]);
4. get error "Exception: Please provide ShowCaseView context"

**Smartphone (please complete the following information):**
 - Device:Redmi note 5 pro
 - OS: Android 9

**Comment by yaa9oub** [comment]
Hey man,

I faced the same error and I noticed that Get.context doesn't provide you with the BuildContext of the ShowCaseWidget.
Get.context returns the current page context.

Since each widget got it's own BuildContext, you have to use the ShowCaseWidget context. 

I looked for a way to get the context for ShowCaseWidget.

Eventually I ended up creating a variable in the current page Controller.

class HomeController extends GetxController {
        late BuildContext showCaseBuildContext;
}

Then I created a function to set showCaseBuildContext with the context provided by ShowCaseWidget inside of the page Controller.

void setContext(context) {
    showCaseBuildContext = context;
  }

and called it in the Builder function.

return ShowCaseWidget(   
              builder: Builder(
                builder: (context) {
                  controller.setContext(context);
                  return HomePage();
                  }
           );

Therefore it will set our variable showCaseBuildContext when it's building the view.

Finally you can use the showCaseBuildContext.

@override
  void onInit() async {
    super.onInit();
    WidgetsBinding.instance.addPostFrameCallback(
      (_) =>
          ShowCaseWidget.of(showCaseBuildContext)?.startShowCase([_one, _two]),
    );
  }

**Comment by mohadel92** [comment]
i will give it a try

**Comment by DhavalRKansara** [comment]
@mohadel92  Does @yaa9oub solutions work for you?

**Comment by vatsaltanna** [comment]
Hi @mohadel92, Solution provided by @yaa9oub seems to solution your issue. Closing this issue for now, feel free to reopen this if issue still persist.
