### ISSUE TITLE
ShowCase doesn't exactly highlight FloatingActionButton

### ISSUE THREAD

**Issue by MariosKoni** [SimformSolutionsPvtLtd/flutter_showcaseview#269]
**Bug**
Showcase can't exactly highlight my floating action button.

**Code**
```
floatingActionButton: _selectedIndex == 2
          ? Showcase(
              key: _one,
              description: 'Tap on it, to start a new session',
              child: FloatingActionButton(
                onPressed: _showNewSessionDialog,
                tooltip: 'Add a new session',
                backgroundColor: Color.fromRGBO(232, 52, 93, 1.0),
                child: const Icon(Icons.add),
              ),
            )
          : null,
```

**Screenshot**
This is a [screenshot](https://drive.google.com/file/d/15xIw5mNXMPxJoFKq5jBvo0Mv9wW6cyyw/view?usp=sharing) of the problem.

**Smartphone**
 - Device: Xiaomi Redmi Note 9 Pro
 - OS: Android 11 (MiUI Global 12.5.8)

**Comment by DhavalRKansara** [comment]
Hi @MariosKoni  We have checked the same on our end and yes it's reproducible, Reason behind the issue is Floating button is having its own animated behaviour where it's come to the floating position from the right bottom corner and in the showcase view we just catch the widget initial location, that's why the issue happens... and it's only happening with the floating button only... To fix it as a workaround you can put a little delay over there while starting the showcase for the floating button and it will be fixed as the floating button will come to its original position and the showcase will catch the perfect location as well...

**Comment by MariosKoni** [comment]
Thanks @DhavalRKansara for the answer!
