### ISSUE TITLE
Showcase for first login, next/previous button and skip button

### ISSUE THREAD

**Issue by Sameer330** [SimformSolutionsPvtLtd/flutter_showcaseview#380]
1. I am trying to construct the showcase widget using a boolean variable for first time login. If I use that I get an error like "cannot use setState() during a widget build".  

* Can you add a parameter inside the show case widget that checks if is the first login. It can be a boolean value that can be provided by the developer.

2. I could not find a next/previous feature to move forward/backward in the app tour.

* Could you add a new button for these?

3. Currently, there is an option to "dismiss()" the showcase but no button to do so.

*  I would like to add buttons to the showcase flyer that could be tapped to dismiss the showcase. Also could be used to create buttons for next/previous.

**Comment by itsAyyazdev** [comment]
Looking for the same thing: next/prev or most importantly Skip.

**Comment by ujas-m-simformsolutions** [comment]
@Sameer330 
1. This is happening because you are trying show showcase while build method hasn't completed. So just add just postFrameCallback like this
```
WidgetsBinding.instance.addPostFrameCallback((_) =>
  ShowCaseWidget.of(context).startShowCase([_one, _two, _three])
);
```
or if there is some kind of animation then wait for that animation to complete by using `Future.delayed(...);`

2.  Currently widgets for showing next/previous tooltip are not available but functions are available so this feature can easily built with `Showcase.withWidget` and using `ShowCaseWidget.of(context).next();` & `ShowCaseWidget.of(context).previous();` on those custom widgets.

3. Similar to above you can `ShowCaseWidget.of(context).dismiss();` to dismiss tooltip

**Comment by Sri-Kumaran-DR** [comment]
yes, this is absolutely necessary!

**Comment by aditya-css** [comment]
Hey @Sameer330, 
Thanks for opening this issue.
For your first point, @ujas-m-simformsolutions's reply would help you with the error and I believe the first time login part can easily be managed outside the package.
For the remaining points, there is already an issue created (#99) and thus I am closing this issue.
