### ISSUE TITLE
Navbar Showcase

### ISSUE THREAD

**Issue by xxJeevesxx** [SimformSolutionsPvtLtd/flutter_showcaseview#406]
Hi, great package, I love the amount of helpful documentation in and out of the code, thank you! I'm struggling to figure this out and hoping someone can provide some guidance. I'm using the persistent nav bar from [https://pub.dev/packages/persistent_bottom_nav_bar_v2](https://pub.dev/packages/persistent_bottom_nav_bar_v2) and I'd like to use a `Showcase` on a bottom navbar item but I can't figure it out. I have wrapped my top level `MaterialApp` in the `ShowCaseWidget` and successfully be able to `Showcase` widgets on my home page but can't figure out how to get a navbar item to work. Any ideas would be greatly appreciated, many thanks!

**Comment by hippedorange22** [comment]
@xxJeevesxx  pass Global Keys to the Navbar items and then reference the keys in the showcase widget.

**Comment by aditya-css** [comment]
Hello @xxJeevesxx,
Thank you for your kind words.
You would require to wrap the widget you want to showcase with `Showcase` but since the persistent nav bar won't allow doing so, I believe it would be best to create an issue in that package asking for a way to pass a class other than the type of `PersistentBottomNavBarItem` to items.
Thanks!
