### ISSUE TITLE
Failed assertion: line 261 pos 15: 'margin == null || margin.isNonNegative': is not true in 3.0.0 version

### ISSUE THREAD

**Issue by Zeinab-Kouhkan** [SimformSolutionsPvtLtd/flutter_showcaseview#458]
In 3.0.0 version When set negative padding to targetPadding get this error:
Failed assertion: line 261 pos 15: 'margin == null || margin.isNonNegative': is not true.
Please restore this feature.

**Comment by rashi-simform** [comment]
Hello @Zeinab-Kouhkan, This doesn't seem related to the package's version and rather relates to the flutter's version. I am closing this issue with this comment. Please feel free to let me know if you need any help with this.

**Comment by axb-c** [comment]
![image](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/79231826/8dfbddc0-2ce7-4b28-a0fe-814237b311d0)

@Zeinab-Kouhkan Check the use of targetPadding, setting a negative value will trigger this crash.

@rashi-simform It is recommended that `margin: targetPadding` be parameterized, and if it is set to a negative value, throw an exception and point to the corresponding globalKey, so that it is easier for people using the showcaseview to troubleshoot the problem.
